### ISSUE TITLE
Issue when running the CLI

### ISSUE THREAD

**Issue by paweljw** [occson/ccs#9]
I performed:

```
$ gem install ccs
```

Running the CLI then results in 

```
$ ccs cp
Traceback (most recent call last):
        3: from /home/.../.rbenv/versions/2.6.6/bin/ccs:23:in `<main>'
        2: from /home/.../.rbenv/versions/2.6.6/bin/ccs:23:in `load'
        1: from /home/.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ccs-3.1.0/exe/ccs:5:in `<top (required)>'
/home/.../.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/ccs-3.1.0/exe/ccs:5:in `require': cannot load such file -- ccs (LoadError)
```

I'm not getting this when running directly from `exe/ccs`, so maybe it's an error in packaging? First one of us that gets a minute should look into it, it's a showstopper.

cc @tkowalewski

**Comment by paweljw** [comment]
Note to self: this seems like it only happens in directories that are managed by rbenv _and_ below Gemfile, e.g.

```
~ # fine
- projects # fine
-- some_ruby_project # boom
-- some_go_project # fine
```

**Comment by tkowalewski** [comment]
Fixed https://github.com/occson/ccs/pull/10
